fake odom added
robotont/robotont_driver pull request #1
Opened 2020-02-06 17:08 UTC by iharsuvorau

Please, check it out.

2020-02-06 17:38 UTC, RValner requested changes
Remove dependency from "joy" and this pull request should then be good to go.

2020-02-06 17:38 UTC, RValner commented on CMakeLists.txt
> +  joy
joy should not be part of the driver package

2020-02-06 17:38 UTC, RValner commented on package.xml
> +  <build_depend>joy</build_depend>
Remove joy dependency

2020-02-06 17:53 UTC, iharsuvorau commented
@RValner No more joy in d4dcc03.

2020-02-07 09:38 UTC, RValner approved these changes

2020-02-07 09:38 UTC, merged